### ISSUE TITLE
ArrayIndexOutOfBoundsException on multi module build

### ISSUE THREAD

**Issue by hazendaz** [trautonen/coveralls-maven-plugin#56]
I have a project https://github.com/hazendaz/waffle.  On this project, we have builds for various versions of tomcat from 5 through 8.  If I run the current 3.0.1 coveralls, it will work if I exclude tomcat 7 and 8.  I've tried a few variations and it seems if I run only tomcat 7 or only tomcat 8, it also works.  I don't really understand what the issue might be here.  We also have multiple builds like this for spring 2 through 4 and those work without issue.  Any ideas?

Here is the stack trace.
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.0.1:report (default-cli) on project waffle-parent: Build error: 247 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.0.1:report (default-cli) on project waffle-parent: Build error
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Build error
    at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.execute(CoverallsReportMojo.java:216)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 247
    at org.eluder.coveralls.maven.plugin.domain.Source.addCoverage(Source.java:92)
    at org.eluder.coveralls.maven.plugin.parser.JaCoCoParser.onEvent(JaCoCoParser.java:61)
    at org.eluder.coveralls.maven.plugin.parser.AbstractXmlEventParser.parse(AbstractXmlEventParser.java:64)
    at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.writeCoveralls(CoverallsReportMojo.java:325)
    at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.execute(CoverallsReportMojo.java:205)
    ... 21 more

**Comment by ceki** [comment]
I have a similar issue with the slf4j project, which is a multi-module maven project. I get the following exception when executing the command

    mvn cobertura:cobertura coveralls:report

Here is the exception.
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 74
        at org.eluder.coveralls.maven.plugin.domain.Source.addCoverage(Source.java:92)
        at org.eluder.coveralls.maven.plugin.parser.CoberturaParser.onEvent(CoberturaParser.java:68)
        at org.eluder.coveralls.maven.plugin.parser.AbstractXmlEventParser.parse(AbstractXmlEventParser.java
        at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.writeCoveralls(CoverallsReportMojo.java:348
        at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.execute(CoverallsReportMojo.java:225)
```

I have several classes which are named exactly the same with the same package name etc. However, that is part of the slf4j architecture which cannot be changed.

**Comment by hazendaz** [comment]
On possibly solution to this would be to create a coveralls branch and on that branch rework the packaging to avoid the issue then have only that branch used to get the coverage scores.  For the project I was working on, I just did it in my local branch, got the scans, then reverted the logic.  I too ultimately decided it was something I couldn't change without greatly affecting those using the product and it wasn't worth fixing just to satisfy usage.

**Comment by trautonen** [comment]
Hacks to get the coverage calculated just doesn't seem right. This issue is quite hard to solve and is now even more harder due to due to scanning source loaders (#63) that allow less strict control where the sources are loaded.

I guess it would be possible to lock the source loading under the reactor module that contains the sources. This would require source loaders to store the module's base directory and when loading the sources the source file's fully qualified path can be compared against the module's base dir. Only source loaders that match the file with their base dir will be applied.

I can give that approach a try at some point. But can't promise any estimates because I'm really busy at the moment.

**Comment by trautonen** [comment]
And just realized that Cobertura does not store the fully qualified file name anywhere. In the aggregate mode it just tells which source roots are scanned and then uses relative file names...

**Comment by liushuainudt** [comment]
try to upgrade to version 3.53. this works for me.
