### ISSUE TITLE
Provide failOnError attribute

### ISSUE THREAD

**Issue by paranoiabla** [trautonen/coveralls-maven-plugin#61]
Hi there,
I have the following project:
- parent
    - module1
    - module2
    - module3

and I have configured the maven surefire AND failsafe plugins to produce results in each of the module's target folder. So to run the build I run the following in the parent folder:

> mvn clean install coveralls:report -Ptest 

which cleans (with success), builds(with success), executes tests(with success), generates jacoco reports(with success) in each module and then it starts executing the coveralls:report but it fails because parent has no source, no tests and hence no jacoco.xml so the coveralls plugin complains with the following:

[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.0.1:report (default-cli) on project platform: I/O operation failed: No coverage report files found -> [Help 1]

here's the stacktrace:
Caused by: java.io.IOException: No coverage report files found
	at org.eluder.coveralls.maven.plugin.util.CoverageParsersFactory.createParsers(CoverageParsersFactory.java:101)
	at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.createCoverageParsers(CoverallsReportMojo.java:231)
	at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.execute(CoverallsReportMojo.java:196)

I'd like to have an attribute like 'failOnError' maybe which can be set to true or false. This way if jacoco.xml was not found the build will continue to the next modules instead of failing.

**Comment by paranoiabla** [comment]
Sorry, just read issue #15 and it seems jacoco does not support aggregates :(
