### ISSUE TITLE
Unprocessable Entity (Couldn't find a repository matching this job.)

### ISSUE THREAD

**Issue by velo** [trautonen/coveralls-maven-plugin#65]
Hi,

I'm using @coveralls + @shippable, but they don't wanna play together...

I already filled an issue with coveralls, but no reply so far.

````
[DEBUG] Configuring mojo org.eluder.coveralls:coveralls-maven-plugin:3.1.0-contaazul-2:report from plugin realm ClassRealm[plugin>org.eluder.coveralls:coveralls-maven-plugin:3.1.0-contaazul-2, parent: sun.misc.Launcher$AppClassLoader@1cd8f55c]
[DEBUG] Configuring mojo 'org.eluder.coveralls:coveralls-maven-plugin:3.1.0-contaazul-2:report' with basic configurator -->
[DEBUG]   (f) coberturaReports = []
[DEBUG]   (f) coverallsFile = /home/shippable/workspace/src/github.com/ContaAzul/ContaAzul/contaazul-coverage-report/target/coveralls.json
[DEBUG]   (f) coverallsUrl = https://coveralls.io/api/v1/jobs
[DEBUG]   (f) dryRun = false
[DEBUG]   (f) jacocoReports = [/home/shippable/workspace/src/github.com/ContaAzul/ContaAzul/contaazul-coverage-report/target/coverage-reports/jacoco.xml]
[DEBUG]   (f) repoToken = secret ;)
[DEBUG]   (f) sagaReports = []
[DEBUG]   (f) scanForSources = true
[DEBUG]   (f) serviceEnvironment = {}
[DEBUG]   (f) skip = false
[DEBUG]   (f) sourceDirectories = [/home/shippable/workspace/src/github.com/ContaAzul/ContaAzul]
[DEBUG]   (f) sourceEncoding = UTF-8
[DEBUG]   (f) project = MavenProject: com.contaazul:contaazul-coverage-report:1.0-SNAPSHOT @ /home/shippable/workspace/src/github.com/ContaAzul/ContaAzul/contaazul-coverage-report/pom.xml
[DEBUG] -- end configuration --
[INFO] Starting Coveralls job for travis-ci (54de2d3cc44f060e00737b83.448.1)
[INFO] Using repository token <secret>
[INFO] Git commit abb7d0c in master
[DEBUG] Complete Job description:
{
  "branch" : "master",
  "dryRun" : false,
  "git" : {
    "branch" : "master",
    "head" : {
      "author_email" : "tiago@contaazul.com",
      "author_name" : "tiago@contaazul.com",
      "committer_email" : "ninjas@contaazul.com",
      "committer_name" : "cacontinous",
      "id" : "abb7d0cc12826cbe90bf90836409fca3ed917fb7",
      "message" : "Merge branch 'hotfix/captcha_receita' into master\n"
    },
    "remotes" : [ {
      "name" : "origin",
      "url" : "git@github.com:ContaAzul/ContaAzul.git"
    } ]
  },
  "pullRequest" : "false",
  "repoToken" : "secret =D",
  "serviceBuildNumber" : null,
  "serviceBuildUrl" : null,
  "serviceEnvironment" : {
    "travis_job_id" : "54de2d3cc44f060e00737b83.448.1",
    "travis_pull_request" : "false"
  },
  "serviceJobId" : "54de2d3cc44f060e00737b83.448.1",
  "serviceName" : "travis-ci",
  "timestamp" : null
}
[INFO] Writing Coveralls data to /home/shippable/workspace/src/github.com/ContaAzul/ContaAzul/contaazul-coverage-report/target/coveralls.json...
[INFO] Processing coverage report from /home/shippable/workspace/src/github.com/ContaAzul/ContaAzul/contaazul-coverage-report/target/coverage-reports/jacoco.xml
[INFO] Successfully wrote Coveralls data in 90322ms
[INFO] Gathered code coverage metrics for 2622 source files with 260264 lines of code:
[INFO] - 85536 relevant lines
[INFO] - 31649 covered lines
[INFO] - 53887 missed lines
[INFO] Submitting Coveralls data to API
[ERROR] Submission failed in 5503ms while processing data
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:52 min
[INFO] Finished at: 2015-02-13T15:36:41-03:00
[INFO] Final Memory: 23M/1004M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.1.0-contaazul-2:report (default-cli) on project contaazul-coverage-report: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.1.0-contaazul-2:report (default-cli) on project contaazul-coverage-report: Processing of input or output data failed
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Processing of input or output data failed
	at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.execute(CoverallsReportMojo.java:218)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.eluder.coveralls.maven.plugin.ProcessingException: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.)
	at org.eluder.coveralls.maven.plugin.httpclient.CoverallsClient.parseResponse(CoverallsClient.java:100)
	at org.eluder.coveralls.maven.plugin.httpclient.CoverallsClient.submit(CoverallsClient.java:89)
	at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.submitData(CoverallsReportMojo.java:346)
	at org.eluder.coveralls.maven.plugin.CoverallsReportMojo.execute(CoverallsReportMojo.java:215)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[INFO] Build failures were ignored.
````

**Comment by trautonen** [comment]
I guess this was caused by the automatic service locator which picked incorrectly Travis? Did #66 fix this issue?

**Comment by velo** [comment]
YES!
